---
- name: Configure HTTPS for zerocarb webserver
  hosts: webservers
  become: yes

  tasks:
    - name: Check if SSL certificates exist
      stat:
        path: /etc/letsencrypt/live/zerocarb.pl/fullchain.pem
      register: ssl_cert

    - name: Create Nginx SSL config file
      copy:
        content: |
          server {
              listen 80;
              server_name zerocarb.pl www.zerocarb.pl;
              
              # Redirect all HTTP requests to HTTPS
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name zerocarb.pl www.zerocarb.pl;
              
              ssl_certificate /etc/letsencrypt/live/zerocarb.pl/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/zerocarb.pl/privkey.pem;
              
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
              
              # Enable HSTS
              add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
              
              root /usr/share/nginx/html;
              index index.html;
              
              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/conf.d/zerocarb.conf
        owner: root
        group: root
        mode: '0644'
      when: ssl_cert.stat.exists
      notify:
        - restart nginx

    - name: Debug nginx config
      command: nginx -t
      register: nginx_config_test
      changed_when: false
      ignore_errors: true
      
    - name: Display nginx config test result
      debug:
        var: nginx_config_test

    - name: Ensure nginx is running and enabled
      systemd:
        name: nginx
        state: restarted
        enabled: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
