---
- name: Configure zerocarb webserver
  hosts: webservers
  become: yes


  tasks:
    - name: Update system packages
      dnf:
        name: "*"
        state: latest
        update_only: yes

    - name: Install required packages 
      dnf:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
          - cronie
        state: present

    - name: Ensure web directory exists with correct permissions
      file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Create initial nginx config (http only)
      copy:
        content: |
          server {
              listen 80;
              server_name zerocarb.pl www.zerocarb.pl;
              
              root /usr/share/nginx/html;
              index index.html;
              
              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/conf.d/zerocarb.conf
        owner: root
        group: root
        mode: '0644'

    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Obtain SSL certificate with Certbot
      command: >
        certbot certonly
        --webroot
        --webroot-path=/usr/share/nginx/html
        --non-interactive
        --agree-tos
        --email jakubkutnik@protonmail.com
        --domains zerocarb.pl,www.zerocarb.pl
      args:
        creates: /etc/letsencrypt/live/zerocarb.pl/fullchain.pem

    - name: Create final SSL nginx config
      copy:
        content: |
          server {
            listen 80;
            server_name zerocarb.pl www.zerocarb.pl;
            return 301 https://$host$request_uri;
          }

          server {
            listen 443 ssl;
            server_name zerocarb.pl www.zerocarb.pl;

            ssl_certificate /etc/letsencrypt/live/zerocarb.pl/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/zerocarb.pl/privkey.pem;

            root /usr/share/nginx/html;
            index index.html;

            location / {
              try_files $uri $uri/ =404;
            }
          }
        dest: /etc/nginx/conf.d/zerocarb.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart nginx

    - name: Set up auto-renewal for SSL certificates
      cron:
        name: "Certbot renewal"
        job: "certbot renew --quiet --no-self-upgrade"
        hour: "3"
        minute: "30"
        weekday: "1"

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
