---
- name: Configure zerocarb webserver
  hosts: webservers
  become: yes


  tasks:
    - name: Update system packages
      dnf:
        name: "*"
        state: latest
        update_only: yes

    - name: Install nginx
      dnf:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
          - cronie
        state: present

    - name: create initial nginx config (http only)
      copy:
        content: |
          server {
              listen 80;
              server_name zerocarb.pl www.zerocarb.pl;
              
              root /usr/share/nginx/html;
              index index.html;
              
              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/conf.d/zerocarb.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart nginx

    - name: Enable and start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Obtain SSL certificate with Certbot
      command: >
        certbot --nginx
        --non-interactive
        --agree-tos
        --email jakubkutnik@protonmail.com
        --domains zerocarb.pl,www.zerocarb.pl
      args:
        creates: /etc/letsencrypt/live/zerocarb.pl/fullchain.pem

    - name: Set up auto-renewal for SSL certificates
      cron:
        name: "Certbot renewal"
        job: "certbot renew --quiet --no-self-upgrade"
        hour: "3"
        minute: "30"
        weekday: "1"

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
